repos:

- repo: local
  hooks:
  - id: pip-compile-requirements
    name: compile requirements.txt
    entry: pip-compile
    language: system
    always_run: false
    files: setup.py
    stages: [push]
    pass_filenames: false
  - id: pip-compile-dev
    name: compile requirements-dev.txt
    entry: pip-compile requirements-dev.in
    language: system
    always_run: false
    files: setup.py
    stages: [push]
    pass_filenames: false
