name: "Compliance OSS"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: OSS Scan
        uses: shoprunner/action-oss@main
